* Free in the dark TODO

** Improvements

*** High priority
 - rename costable and dummies (cam.dummy1=DisplayedRoom?, cam.dummy3=strange offset?,cameraZoneDefTable.dummy1=room?)
 - why do camera use room x,y,z ? (with 0 it works perfectly)
 - change all unsigned to uXX?

*** Low priority
 - hardColStruct and sceZoneStruct are the same?
 - Detect BIG_ENDIAN
 - remove version.c and version.h
 - move many functions out of main.c
 - READ_LE_U32 is sometimes in ifdef, but there is already an ifdef in READ_LE_U32
 - loadPakToPtr and loadPak very similar?
 - what are the 10 "tailing bytes" after each file in PAK? => seems to be just margin

** Crashs

*** Reading floors seems strange (reading camera stuff in ETAGE04 crashes)

*** 1st zombie appears

*** Demo AITD1 64 bits
    Thread 1 "fitd" received signal SIGSEGV, Segmentation fault.
    processAnimRotation (bodyPtr=bodyPtr@entry=0x7fffffffd948, bp=bp@entry=1, bx=bx@entry=15) at anim.c:261
    261	  short int oldRotation = *(short int*)animVar4;

    on demo, only if 64 bits
    
    Due to *bodyPtr taken as a pointer when looking 4 bytes later?
    Bad fix : animBufferPtr=(u8*)((u32)animBufferPtr)
    
    When is bodyPtr filled with 32 pointers? How is it working in 64 bits? 

*** Demo AITD1 64/32 bits : Fixed
    Unsupported ZV type in copyObjectToActor
    if was a problem in initEngine when fixing maxObjects = 300 for AITD1.
    only 291 objects where read in file, I initialized 300 objects before reading

*** selectHero
    Crash in
    printText(CVars[getCVarsIdx(INTRO_HERITIERE)]+1,165,5,314,194,2,15);
    The text is well uncompressed...
    No portrait drawn.

** Bugs
    Now that the crash is fixed, on 64 bits the walking animation starts with a teleportation...
    
    Some 3d models are blinking.

*** High priority
 - Fix warnings
 - Fix crash

*** Low priority
 - sdlmixer not checked in configure



